### ISSUE TITLE
Empty reports

### ISSUE THREAD

**Issue by ashenoy864** [yu210148/gvm_install#13]
Hello,

Used your wonderful script to install GVM and the install went through fine. The daemons are all running, I am able to login to the UI. However, when I create a task to scan a target, I am returned a report that only contains the "Summary" and "Result Overview". The "Result per Host" is empty.
Not sure what the issue might be. Any clues on what I have done wrong ?
Thanks.

**Comment by yu210148** [comment]
Humm,

I've seen that before with different versions of the scanner. I haven't run
this in a while and because the script pulls in the latest from their git
repo it's kind of at the mercy of their development. So, you may not have
done anything wrong it may just be that there's something broken in the
scanner itself at the moment.

Kev.

**Comment by yu210148** [comment]
The other thing you might want to check is if nmap is installed and working on your system. I put it in one of the apt-get statements in the script but something may be up with it. I've seen the results come back empty when it's not installed. Finding a target and running 'nmap <target_ip_address>' where target_ip_address is a valid device on your network may tell us if something is wrong with it.

kev.
