### ISSUE TITLE
Service unavailable after boot

### ISSUE THREAD

**Issue by aretsmarvin** [yu210148/gvm_install#16]
Hi guys,

This script worked fine, untill a few days ago. Now everytime after boot, when I try to verify the scanners, I get this error message:
Service unavailable.

When I rerun the install script, it works again, but this cost way to much time every time I boot up. Any toughts what it could be?

**Comment by yu210148** [comment]
Sorry for the delayed reply on this. I just ran into something that sounds like this while adapting the script to run on Debian. The trouble seemed to come from the hard coded references to /opt/gvm/lib/python3.8/site-packages. Unlike Ubuntu 20.04, Debian 10 uses python3 version 3.7 rather than 3.8 so I've adjusted the script to use the actual version of python installed rather than assuming version 3.8. 

I was able to resolve the issue in testing by editing /etc/systemd/system/openvas.service, gsa.service, and gvm.service to reflect the path /opt/gvm/lib/python3.7/site-packages present on Debian 10. When I restarted, the scanner started and I was able to verify both with the web interface and command line. 

You may want to take a look at /opt/gvm/lib and see what the subdirectory to site-packages is on your system and edit the service unit files to match.

kev.

**Comment by aretsmarvin** [comment]
But I am using Ubuntu 20.04. And It's only using Python 3.8 (as far as I can see).

So I think it is another issue?

**Comment by yu210148** [comment]
Humm, could I get you to post copies of your /etc/systemd/system/openvas.service, /etc/systemd/system/gsa.service, and /etc/systemd/system/gvm.service files so I can compare them to what I've got on my working versions? 

If possible, could I also get the output of `sudo systemctl status openvas`, `sudo systemctl status gsa`, and `sudo systemctl status gvm` on your system when it's in it's non-working state?

Thanks in advance.

kev.

**Comment by plgrooms** [comment]
I just installed the GVM 20.08 and when I try to verify the default scanner i receive Service Unavailable. I used the following script to install on Ubuntu 20.04 
wget https://raw.githubusercontent.com/yu210148/gvm_install/master/install_gvm.sh
Can anyone help a Noob please?

**Comment by yu210148** [comment]
Hi there,

I've put a note about some of the post-install issues I've run into in the
readme file (see below as well) but I'm not sure it's the same as what
you're describing. Regardless, if you haven't tried giving it a restart try
that then leave it running for a few hours before trying again. It seems
there are sometimes timing issues that sort themselves out with a bit of
run-time.

Here's what I have in the readme:

Seems, that after completing the script for version 20 the machine needs to
be restarted. Then you should be able to log into the web interface. Once
logged in, head over to Administration-->Feed Status. If any of the feeds
show a status of 'Update in progress' wait until they're completed. While
you're waiting, log in to a command prompt on the machine and become the
GVM user (e.g., sudo -i, su gvm). List the gvm user's crontab file with
'crontab -l' and manually execute the commands shown there (e.g.,
'/opt/gvm/sbin/greenbone-feed-sync --type SCAP') once the feed status
changes from 'Update in progress' to the feed's actual status. When you run
the commands from the crontab the feed status update as shown in the web
interface will change back to show that it's updating. Again, wait for it
to complete before running the next line from the crontab. Once all the
feeds are showing versions that look like dates (e.g., 20201229T1131) and
the status is no longer showing as updating you should be able to start a
scan using the OpenVAS Scanner under Scans-->Tasks-->New Task.

Hope that helps.

kev.

**Comment by yu210148** [comment]
Going to close this off for now but we can re-open it again in the future if needed.
