### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Tonantems** [yu210148/gvm_install#21]
Hi, I used your script to install openvas (GVM 11). It's helpful for me. But I have some problems after Installation.
It showed : The installation is done, but there may still be an update in progress.
Is that mean I install complete ? Then how do I operating GVM 11 after installation complete.
thanks!

**Comment by yu210148** [comment]
Hi there,

The message is there because there seems to be some sort of timing issue once the script is done that I haven't been able to figure out. See Issue #9 & Issue #10 for more info on that. The short version is that the thing may not be ready for you to log in right away once the script is done and may need the machine that you ran it on to be restarted before it lets you log in.

To answer your second question, the thing uses a web interface so to use it first determine what IP address the machine has--`ip a` is one command that'll show it--then point a web browser to https://<ip-address-of-machine>, replacing <ip-address-of-machine> with whatever the actual IP address is. 

It uses a self-signed certificate for the web interface so you'll get a warning message from the web browser but in this case, it should be safe to proceed.

kev.
