### ISSUE TITLE
Error after start the scan

### ISSUE THREAD

**Issue by Shpil93** [yu210148/gvm_install#33]
Thank you for title about GVM.
After instulled GVM 11 on ubuntu 20.04 and started scan I get the error message: "There is a pending feed update and the task ran with an outdated feed version". What is it and how I solve of this problem?
Thank you.

**Comment by yu210148** [comment]
Hi there,

It sounds like there's a newer version of one or more of the feeds that it's using. The simplest solution is to leave the thing running and online for more than 24 hours. The install script sets automated jobs to check for feed updates at random times once a day. 

If you don't want to wait; what I usually do, is open the web interface and navigate to Administration-->Feed Status. Then open up a terminal window and ssh into the machine running GVM. Once there, become root with `sudo -i` then su to become the 'gvm' user with `su gvm`. Once there, you can take a look at the 'gvm' user's crontab with `crontab -l`.

Here's what mine looks like:

> gvm@ubuntu-gvm-vm:/root$ crontab -l
> 3 4 * * * /opt/gvm/sbin/greenbone-feed-sync --type SCAP
> 35 7 * * * /opt/gvm/bin/greenbone-nvt-sync
> 59 11 * * * /opt/gvm/sbin/greenbone-feed-sync --type CERT
> 1 19 * * * /opt/gvm/sbin/greenbone-feed-sync --type GVMD_DATA
> 32 4 * * * /usr/bin/sudo /opt/gvm/sbin/openvas --update-vt-info

The numbers before the asterisks will be different on yours but it's the bits after them that we need for this.

Here's what I mean:

![image](https://user-images.githubusercontent.com/1334385/114020087-308e6f00-983d-11eb-92cf-c5e204f1dce7.png)


You can run each of the commands from the crontab manually in the terminal as the 'gvm' user. For example to run the first one enter `/opt/gvm/sbin/greenbone-feed-sync --type SCAP` into the terminal and press enter. When you do, the feed status in the web interface will change to 'Update in progress'. The command will finish in the terminal before that changes in the web interface. You need to wait until it stops saying 'Update in progress in the web interface before running the next command.



While you're looking at the crontab check to see what the numbers are before the asterisks. They represent the time of day that the command should run. In the install script, I had it pick random times for each to avoid having everyone who uses this clobbering the update server at the same time. The downside to this approach is that there is a chance yours are too close together. For example, if my CERT update is scheduled to happen at 11:59 as above, if my nvt-sync were to be scheduled at 11:57 I'd have a problem because it wouldn't be finished by the time my CERT update happened. This would cause the CERT update to fail. It's possible this is what you're running into.

kev.

**Comment by Shpil93** [comment]
Thank you!!! I'm going to do it today!

**Comment by Shpil93** [comment]
It's my crontab file:

**Comment by yu210148** [comment]
Hi again,

They changed how it does it between version 11 and version 20 so what you see is how it was supposed to work in version 11. I should really get rid of the version 11 option from the installer as it's now past it's end-of-life according to Greenbone (https://community.greenbone.net/t/gvm-11-end-of-life-initial-release-2019-10-14/3674). So it really shouldn't be an option anymore.

kev.

**Comment by yu210148** [comment]
I just pushed a commit that removes the option to install version 11. They may not be updating the feeds for it anymore which may also be why you're seeing the message about it being out of date. 

If it were me I'd start a fresh install, have it install version 20 then go from there. 

I'm going to close this issue off on github for now but we can re-open it if we want to later on. 

kev.
