### ISSUE TITLE
Unable to install GVM/Open-Vas

### ISSUE THREAD

**Issue by knindza22** [yu210148/gvm_install#78]
I have installed Open-vas while back but too messy using virtual box and what not. Now i install ubuntu on ESXI and run the sh available on this thread and does not matter if i use 20 or 21 it just will not work. the localhost comes up with unable to connect. Internet works fine, firewall is off. I have tried via loopback and machine ip adders. From what i have read this installer should just install and be working and i have no clue why not. i am not very strong in Linux.

**Comment by QuaiGoner** [comment]
send some logs from installing process

**Comment by knindza22** [comment]
i am sorry i reformatted the hdd and tried with another Linux distro and different directions. i will reload with this one and send you something,.

**Comment by knindza22** [comment]
i figured out the issue. i was loading gvm on to 22.04 instead of 20.04, once i used 20.04 ubuntu it worked like a charm. did not have top do anything. On the other note, am i able to upgrade ubuntu to newest without breaking the gvm?

**Comment by yu210148** [comment]
Ah, gotcha, yes I haven't had a chance to look at 22.04 yet so haven't
tried it on there yet.

Kev.

**Comment by yu210148** [comment]
Humm, I don't have any experience with ESXI so I don't know what it might
be doing to you that could cause the issue. I know there was someone who
was trying to use it on AWS and running into issues that weren't there in a
local vm or on a bare metal install of Ubuntu. Something similar might be
going on here.

Does ESXI do bridge mode networking? If so, what happens if you connect to
it from another machine on your network? I'm wondering if it may not be
listening on the localhost interface.

Kev.

**Comment by knindza22** [comment]
I finally decided to go back and so everything from scratch on 20.04, got it working on this and then upgraded to 22.04 and believe it or not it is still working so not sure if i have missed something or not but than you for following up. Keep up the good work.
